version: "3"

includes:
  webapp:
    taskfile: ./apps/webapp/Taskfile.yaml
    dir: ./apps/webapp
  devbox-services:
    taskfile: ./libs/devbox-services/Taskfile.yaml
    dir: ./libs/devbox-services
  asyncapi:
    taskfile: ./libs/asyncapi/Taskfile.yaml
    dir: ./libs/asyncapi
  gorm:
    taskfile: ./libs/gorm/Taskfile.yaml
    dir: ./libs/gorm

tasks:
  skaffold:run:
    cmd: skaffold run
    desc: Run a kubernetes pipeline locally
  skaffold:dev:
    aliases:
      - skaffold:watch
    cmd: skaffold dev
    desc: Run a kubernetes pipeline locally in development mode, watch and re-iterate