version: "3"

includes:
  webapp:
    taskfile: ./apps/webapp/Taskfile.yaml
    dir: ./apps/webapp
  devbox-services:
    taskfile: ./libs/devbox-services/Taskfile.yaml
    dir: ./libs/devbox-services
