name: DB-Migrate
on:
  workflow_dispatch:
jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create empty .env file
        run: touch .env
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: "true"
          devbox-version: "0.14.0"
          project-path: "./libs/devbox-minimal"
      - name: Run DB Migration Script
        run: devbox run -- task gorm:migrate
        env:
          POSTGRESQL_DSN: ${{ secrets.DB_MIGRATE_POSTGRESQL_DSN }}
